//typedef struct WINDOW WINDOW;
typedef struct WINDOW {
    unsigned short flags;
    unsigned short pixel_x;
    int* text_start;
    int* text_start2;
    int unknown1;
    int unknown2;
    int text_offset;
    int unknown3;
    int text_offset2;
    unsigned short window_area;
    unsigned short window_x;
    unsigned short window_y;
    unsigned short window_width;
    unsigned short window_height;
    unsigned short text_x;
    unsigned short text_y;
    unsigned short unknown4;
    unsigned short delay;
    unsigned short unknown5;
    unsigned short cursor_x;
    unsigned short cursor_y;
    int unknown6;
    int unknown7;
    unsigned short page;
    unsigned short unknown8;
    int unknown9;
    int unknown10;
    int unknown11;
} WINDOW;
