name: Build & Test master
on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - develop
jobs:
  build:
    name: Patch building & Publishing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build the patch
        run: "docker run --rm -u root -v ${PWD}:/home/m2gba/src lorenzooone/m2gba_translation:patch_builder"
      - name: Auto-Release the patch
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "nightly-latest"
          prerelease: true
          title: "Automatic Build"
          files: |
            LICENSE
            out/m12.ips
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unpack the required data for the tests
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$TESTING_PASSPHRASE" --output bin/testing_required_data.zip bin/testing_required_data.zip.gpg
          sudo apt install unzip
          unzip -q bin/testing_required_data.zip -d bin
        env:
          TESTING_PASSPHRASE: ${{ secrets.TESTING_PASSPHRASE }}
      - name: Test the code
        run: "docker run --rm -u root -v ${PWD}:/home/m2gba/src lorenzooone/m2gba_translation:tester"
