name: Test PR
on:
  pull_request_target:
    branches: master

jobs:
  test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Unpack the required data for the tests
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="$TESTING_PASSPHRASE" --output extractor/bin/testing_required_data.zip extractor/bin/testing_required_data.zip.gpg
          sudo apt install unzip
          unzip -q extractor/bin/testing_required_data.zip -d extractor/bin
        env:
          TESTING_PASSPHRASE: ${{ secrets.TESTING_PASSPHRASE }}
      - uses: actions/checkout@v3
        name: Test the code
        ref: ${{ github.event.pull_request.head.sha }}
        run: |
          cp extractor/bin/* bin/
          docker run --rm -u root -v ${PWD}:/home/m2gba/src lorenzooone/m2gba_translation:tester
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-report
          path: out/test.log
